---
include:
  - project: 'common/helm-charts'
    ref: master
    file: '/.gitlab-ci/argocd.yml'

.update:
  variables:
    BRANCH: $CI_COMMIT_BRANCH
  before_script:
    - CI_PUSH_REPO=`echo "$CI_REPOSITORY_URL $GIT_PUSH_ACCESS_TOKEN" | sed 's/^.*\(@.*\)\s\(.*\)/https:\/\/oauth2:\2\1/g'`
    - git remote set-url origin $CI_PUSH_REPO
    - git config user.name "ci-bot"
    - git config user.email "ci-bot@noreply.$CI_SERVER_HOST"
    - cd $CHART_PATH


stages:  # List of stages for jobs, and their order of execution
  - linters
  - build
  - deploy

build:
  stage: build
  variables:
    CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:$TAG.$CI_PIPELINE_IID
  tags:
    - shell
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CONTAINER_IMAGE} -f Dockerfile .
    - docker push ${CONTAINER_IMAGE}
  only:
    refs:
      - master
      - dev

