stages:
    - deploy

deploy:
  stage: deploy
  image: node:18
  script:
    - npm install -f
    - npm run build
    - npm i wrangler -g
    - npx wrangler pages deploy --branch=CI_COMMIT_BRANCH
  only:
    refs:
      - main
      - dev

