---

webapi:
  envs:
    Serilog__WriteTo__0__Args__formatter: "Serilog.Formatting.Compact.RenderedCompactJsonFormatter, Serilog.Formatting.Compact"

  service:
    name: "dedicated-product-dashboard-ui"
  
  imagePullSecrets:
    - name: gitlab-zenno-registry-capmonstercloud
  
  autoscaling:
    minReplicas: 1
    maxReplicas: 1

  health:
    startupProbe: false
    livenessProbe: false
    readinessProbe: false

...